<?php
return [
    "shopkeepers" => [
        [
            "id" => 0,
            "name" => "MC Donalds",
            "email" => "mcdonadls@gmail.com",
            "password" => "mcdonalds123",
            "address" => [
                // "street" => "",
                // "city" => "",
                // "lat" => "",
                // "long" => "",
            ],
            "image" => "https://rs-menus-api.roocdn.com/images/9c3c0ca6-f2d1-4445-be8e-6f846a49fd9e/image.jpeg?width=533&height=300&auto=webp&format=jpg&fit=crop",
            // "piva" => "",
            "timetables" => [
                "Monday" => "07:00AM - 09:00PM",
                "Tuesday" => "07:00AM - 09:00PM",
                "Wednesday" => "07:00AM - 09:00PM",
                "Thursday" => "07:00AM - 09:00PM",
                "Friday" => "07:00AM - 09:00PM",
                "Saturday" => "08:00AM - 09:00PM",
                "Sunday" => "08:00AM - 09:00PM"
            ],
            "rating" => "9",
        ],
        [
            "id" => 0,
            "name" => "Pizzeria Reginella",
            "email" => "pizzeriareginella@gmail.com",
            "password" => "reginella123",
            "address" => [
                // "street" => "",
                // "city" => "",
                // "lat" => "",
                // "long" => "",
            ],
            "image" => "https://rs-menus-api.roocdn.com/images/79519415-0a4c-47b6-9ee5-0235af7c9022/image.jpeg?width=533&height=300&auto=webp&format=jpg&fit=crop",
            // "piva" => "",
            "timetables" => [
                "Monday" => "07:00AM - 09:00PM",
                "Tuesday" => "07:00AM - 09:00PM",
                "Wednesday" => "07:00AM - 09:00PM",
                "Thursday" => "07:00AM - 09:00PM",
                "Friday" => "07:00AM - 09:00PM",
                "Saturday" => "08:00AM - 09:00PM",
                "Sunday" => "08:00AM - 09:00PM"
            ],
            "rating" => "8",
        ],
        [
            "id" => 0,
            "name" => "Starbucks",
            "email" => "Starbucks@gmail.com",
            "password" => "Starbucks123",
            "address" => [
                // "street" => "",
                // "city" => "",
                // "lat" => "",
                // "long" => "",
            ],
            "image" => "https://rs-menus-api.roocdn.com/images/9c3c0ca6-f2d1-4445-be8e-6f846a49fd9e/image.jpeg?width=533&height=300&auto=webp&format=jpg&fit=crop",
            // "piva" => "",
            "timetables" => [
                "Monday" => "07:00AM - 09:00PM",
                "Tuesday" => "07:00AM - 09:00PM",
                "Wednesday" => "07:00AM - 09:00PM",
                "Thursday" => "07:00AM - 09:00PM",
                "Friday" => "07:00AM - 09:00PM",
                "Saturday" => "08:00AM - 09:00PM",
                "Sunday" => "08:00AM - 09:00PM"
            ],
            "rating" => "7",
        ],
        [
            "id" => 0,
            "name" => "Sushi Club",
            "email" => "sushiclub@gmail.com",
            "password" => "sushi123",
            "address" => [
                // "street" => "",
                // "city" => "",
                // "lat" => "",
                // "long" => "",
            ],
            "image" => "https://www.mizusushi.it/wp-content/uploads/2020/10/026_1-scaled.jpg",
            // "piva" => "",
            "timetables" => [
                "Monday" => "07:00AM - 09:00PM",
                "Tuesday" => "07:00AM - 09:00PM",
                "Wednesday" => "07:00AM - 09:00PM",
                "Thursday" => "07:00AM - 09:00PM",
                "Friday" => "07:00AM - 09:00PM",
                "Saturday" => "08:00AM - 09:00PM",
                "Sunday" => "08:00AM - 09:00PM"
            ],
            "rating" => "7",
        ],
        [
            "id" => 0,
            "name" => "Principe di Kebab Ali baba",
            "email" => "kebab@gmail.com",
            "password" => "kebab123",
            "address" => [
                // "street" => "",
                // "city" => "",
                // "lat" => "",
                // "long" => "",
            ],
            "image" => "https://media-cdn.tripadvisor.com/media/photo-s/0e/50/98/36/ali-baba-doner-kebab.jpg",
            // "piva" => "",
            "timetables" => [
                "Monday" => "07:00AM - 09:00PM",
                "Tuesday" => "07:00AM - 09:00PM",
                "Wednesday" => "07:00AM - 09:00PM",
                "Thursday" => "07:00AM - 09:00PM",
                "Friday" => "07:00AM - 09:00PM",
                "Saturday" => "08:00AM - 09:00PM",
                "Sunday" => "08:00AM - 09:00PM"
            ],
            "rating" => "2",
        ],
        [
            "id" => 0,
            "name" => "Burger King",
            "email" => "burgerking@gmail.com",
            "password" => "burger123",
            "address" => [
                // "street" => "",
                // "city" => "",
                // "lat" => "",
                // "long" => "",
            ],
            "image" => "https://www.foodserviceweb.it/wp-content/uploads/sites/4/2021/01/burger-king-logo-rebrand-bk-jkr_dezeen_2364_social_0.jpg",
            // "piva" => "",
            "timetables" => [
                "Monday" => "07:00AM - 09:00PM",
                "Tuesday" => "07:00AM - 09:00PM",
                "Wednesday" => "07:00AM - 09:00PM",
                "Thursday" => "07:00AM - 09:00PM",
                "Friday" => "07:00AM - 09:00PM",
                "Saturday" => "08:00AM - 09:00PM",
                "Sunday" => "08:00AM - 09:00PM"
            ],
            "rating" => "10",
        ],
        [
            "id" => 0,
            "name" => "Burrito's Way",
            "email" => "BurritoWay@gmail.com",
            "password" => "burrito123",
            "address" => [
                // "street" => "",
                // "city" => "",
                // "lat" => "",
                // "long" => "",
            ],
            "image" => "https://www.foodserviceweb.it/wp-content/uploads/sites/4/2021/01/burger-king-logo-rebrand-bk-jkr_dezeen_2364_social_0.jpg",
            // "piva" => "",
            "timetables" => [
                "Monday" => "07:00AM - 09:00PM",
                "Tuesday" => "07:00AM - 09:00PM",
                "Wednesday" => "07:00AM - 09:00PM",
                "Thursday" => "07:00AM - 09:00PM",
                "Friday" => "07:00AM - 09:00PM",
                "Saturday" => "08:00AM - 09:00PM",
                "Sunday" => "08:00AM - 09:00PM"
            ],
            "rating" => "8",
        ],
        [
            "id" => 0,
            "name" => "La Sangria",
            "email" => "sangria@gmail.com",
            "password" => "sangria123",
            "address" => [
                // "street" => "",
                // "city" => "",
                // "lat" => "",
                // "long" => "",
            ],
            "image" => "https://just-eat-prod-eu-res.cloudinary.com/image/upload/c_fill,f_auto,q_auto,w_450,h_450,d_it:cuisines:pizza-3.jpg/v1/it/restaurants/224023.jpg",
            // "piva" => "",
            "timetables" => [
                "Monday" => "07:00AM - 09:00PM",
                "Tuesday" => "07:00AM - 09:00PM",
                "Wednesday" => "07:00AM - 09:00PM",
                "Thursday" => "07:00AM - 09:00PM",
                "Friday" => "07:00AM - 09:00PM",
                "Saturday" => "08:00AM - 09:00PM",
                "Sunday" => "08:00AM - 09:00PM"
            ],
            "rating" => "8",
        ],
        [
            "id" => 0,
            "name" => "Chuan Xiang Ju Gastronomia Cinese",
            "email" => "Xiang@gmail.com",
            "password" => "Xiang123",
            "address" => [
                // "street" => "",
                // "city" => "",
                // "lat" => "",
                // "long" => "",
            ],
            "image" => "https://tb-static.uber.com/prod/image-proc/processed_images/253b22d7c39d15c2bfb1ff546aea6451/820883a48567670acbd720bc76391291.jpeg",
            // "piva" => "",
            "timetables" => [
                "Monday" => "07:00AM - 09:00PM",
                "Tuesday" => "07:00AM - 09:00PM",
                "Wednesday" => "07:00AM - 09:00PM",
                "Thursday" => "07:00AM - 09:00PM",
                "Friday" => "07:00AM - 09:00PM",
                "Saturday" => "08:00AM - 09:00PM",
                "Sunday" => "08:00AM - 09:00PM"
            ],
            "rating" => "5",
        ],
        [
            "id" => 0,
            "name" => "Mi prendi in Gyros",
            "email" => "gyros@gmail.com",
            "password" => "gyros123",
            "address" => [
                // "street" => "",
                // "city" => "",
                // "lat" => "",
                // "long" => "",
            ],
            "image" => "https://resizer.deliverect.com/DItIPAHZ2UIOpbjq4QsDfJ1cX7pX7U7H4Vtg9XhKLDg/rt:fill/w:1024/h:1024/g:ce/el:0/aHR0cHM6Ly9zdG9yYWdlLmdvb2dsZWFwaXMuY29tL2lrb25hLWJ1Y2tldC1wcm9kdWN0aW9uL2ltYWdlcy82MjgzOGQ5MDNmNDY5MDJjY2Q1ZTRiNGQvUGl0YV9GYWxhZmVsLTYzN2RmNjBlYTNmMWFjNGZhNDkwOGY3My5qcGc=",
            // "piva" => "",
            "timetables" => [
                "Monday" => "07:00AM - 09:00PM",
                "Tuesday" => "07:00AM - 09:00PM",
                "Wednesday" => "07:00AM - 09:00PM",
                "Thursday" => "07:00AM - 09:00PM",
                "Friday" => "07:00AM - 09:00PM",
                "Saturday" => "08:00AM - 09:00PM",
                "Sunday" => "08:00AM - 09:00PM"
            ],
            "rating" => "9.0",
        ],
    ],
    "types" => [
        "name" => [
            "italiano",
            "americano",
            "cinese",
            "giapponese",
            "messicano",
            "indiano",
            "greco",
            "turco",
            "spagnolo",
            "russo",
        ]
    ],
    "categories" => [
        "name" => [
            "bibite",
            "alcol",
            "hamburger",
            "piadine",
            "dessert",
            "kebab",
            "pasta",
            "pizza",
            "poke",
            "sandwich",
            "sushi",
            "tacos",
        ]
    ],
    "products" => [
        [
            "id" => 0,
            "name" => "patatine",
            "price" => "2.90",
            "available" => 1,
            "ingredients" => "patatine fritte",
            "image" => "https://rs-menus-api.roocdn.com/images/af746bd6-c814-4508-ae80-951ddecd4a8a/image.jpeg?width=543&height=305&auto=webp&format=jpg&fit=crop",
        ],
        [
            "id" => 1,
            "name" => "grand crispy McBacon",
            "price" => "7.10",
            "available" => 1,
            "ingredients" => "bacon, hamburger, cheddar, salsa crispy",
            "image" => "https://rs-menus-api.roocdn.com/images/a9618a3d-ea13-4f45-945c-936b67fd673d/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "id" => 2,
            "name" => "coca-cola",
            "price" => "3.00",
            "available" => 1,
            "ingredients" => "liquido gassoso zuccherato",
            "image" => "https://rs-menus-api.roocdn.com/images/660ad39f-d513-42fc-b27e-8f083d548fdf/image.jpeg?width=543&height=305&auto=webp&format=jpg&fit=crop",
        ],
        [
            "id" => 3,
            "name" => "pizza margherita",
            "price" => "5.00",
            "available" => 1,
            "ingredients" => "salsa di pomodoro, fiordilatte di agerola, basilico",
            "image" => "https://italianspizza.it/wp-content/uploads/2022/06/FAMILY-PIZZA-MARGHERITA-online-pizza-sconti-eventi-feste-delivery-consegna-a-domicilio-san-colombano-al-lambro-lambrinia-monteleone-lodi-milano-italia.png",
        ],
        [
            "id" => 4,
            "name" => "pizza patatine e wurstel",
            "price" => "7.50",
            "available" => 1,
            "ingredients" => "salsa di pomodoro, patatine fritte, wurstel",
            "image" => "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6EfKp4WEmv4ED2UzSFHg3Dq86reMHi97FBHMZG7cMJD0zArx7u_opsvoBkwkWo1w4UIs&usqp=CAU",
        ],
        [
            "id" => 5,
            "name" => "pizza quattro stagioni",
            "price" => "8.00",
            "available" => 1,
            "ingredients" => "salsa di pomodoro, funghi, carciofi, peperoni, prosciutto cotto",
            "image" => "https://upload.wikimedia.org/wikipedia/commons/4/42/Pizza_Quattro_Stagioni_transparent.png?width=858&height=542",
        ],
        [
            "id" => 6,
            "name" => "sangria tradicional rossa",
            "price" => "13.00",
            "available" => 1,
            "ingredients" => "vino rosso, brandy, cointreau, gin, frutta",
            "image" => "https://banner2.cleanpng.com/20180701/bzg/kisspng-sangria-red-wine-juice-cocktail-tragos-5b386f2fd2ac39.2934068115304251358629.jpg",
        ],
        [
            "id" => 7,
            "name" => "paella di marisco",
            "price" => "18.00",
            "available" => 1,
            "ingredients" => "frutti di mare",
            "image" => "https://www.saporedimare.it/wp-content/uploads/elementor/thumbs/Paella-carne-pesce-plbjf523mkqld4kaarqymwykuj7dw7dh0e688bjrf2.png",
        ],
        [
            "id" => 8,
            "name" => "gazpacho andaluz",
            "price" => "8.90",
            "available" => 1,
            "ingredients" => "zuppa fredda di verdure crude e pomodoro",
            "image" => "https://yimages360.s3.amazonaws.com/products/2021/06/60b8e7a4bef2d/1x.jpg",
        ],
        [
            "id" => 9,
            "name" => "Cappuccino",
            "price" => "2.60",
            "available" => 1,
            "ingredients" => "Latte caldo ed espresso con una soffice e golosa crema di latte",
            "image" => "https://f.roocdn.com/images/menu_items/98014100/item-image.jpg?width=543&height=305&auto=webp&format=jpg&v=1674467059&fit=crop",
        ],
        [
            "id" => 10,
            "name" => "Caffe Americano",
            "price" => "2.50",
            "available" => 1,
            "ingredients" => "Caffe espresso e acqua calda come la classica ricetta americana",
            "image" => "https://f.roocdn.com/images/menu_items/98014104/item-image.jpg?width=543&height=305&auto=webp&format=jpg&v=1674467059&fit=crop",
        ],
        [
            "id" => 11,
            "name" => "Toast Classico",
            "price" => "6.90",
            "available" => 1,
            "ingredients" => "Pane toast con farina integrale, prosciutto cotto alta qualita, edamer",
            "image" => "https://f.roocdn.com/images/menu_items/98014029/item-image.jpg?width=560&height=315&auto=webp&format=jpg&v=1674467059&fit=crop",
        ],
        [
            "id" => 12,
            "name" => "Riso alla cantonese",
            "price" => "4.00",
            "available" => 1,
            "ingredients" => "Riso saltato con prosciutto, piselli ed uovo",
            "image" => "https://images.fidhouse.com/fidelitynews/wp-content/uploads/sites/6/2016/03/1456829520_d14699eab543f3b24be96d83a9fa22b34846fce0-321023390.jpg",
        ],
        [
            "id" => 13,
            "name" => "Onigiri spicy",
            "price" => "5.00",
            "available" => 1,
            "ingredients" => "Salmone crudo e salsa maionese piccante",
            "image" => "https://rs-menus-api.roocdn.com/images/ab985cb8-fb29-4cad-870d-18883a4d23eb/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "id" => 14,
            "name" => "Sashimi sake",
            "price" => "5.00",
            "available" => 1,
            "ingredients" => "Fettine di salmone crudo",
            "image" => "https://rs-menus-api.roocdn.com/images/7824972b-dbf0-4924-936e-2054078680c8/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "id" => 15,
            "name" => "Panino Kebab",
            "price" => "6.00",
            "available" => 1,
            "ingredients" => "Kebab, insalata, pomodoro, salsa piccante, cipolla , salsa yogurt",
            "image" => "https://d2j6dbq0eux0bg.cloudfront.net/images/62400814/2367230254.jpg",
        ],
        [
            "id" => 16,
            "name" => "Arrotolato Kebab",
            "price" => "6.00",
            "available" => 1,
            "ingredients" => "Kebab, insalata, pomodoro, salsa piccante, cipolla , salsa yogurt",
            "image" => "https://qualitifood.com/wp-content/uploads/brizy/imgs/piada-kebab-tagliato-545x545x0x68x545x409x1562337866.png",
        ],
        [
            "id" => 17,
            "name" => "Focaccia bianca",
            "price" => "4.00",
            "available" => 1,
            "ingredients" => "Focaccia bianca",
            "image" => "https://content.dambros.it/uploads/2016/04/19103803/0000121304.jpg",
        ],
        [
            "id" => 18,
            "name" => "Bacon King",
            "price" => "8.10",
            "available" => 1,
            "ingredients" => "Due hamburger di manzo alla griglia con 8 fette di bacon, cheddar, ketchup e maionese",
            "image" => "https://f.roocdn.com/images/menu_items/19526413/item-image.jpg?width=543&height=305&auto=webp&format=jpg&v=1675186254&fit=crop",
        ],
        [
            "id" => 19,
            "name" => "Sprite",
            "price" => "3.80",
            "available" => 1,
            "ingredients" => "Bibita Sprite",
            "image" => "https://f.roocdn.com/images/menu_items/19526353/item-image.jpg?width=560&height=315&auto=webp&format=jpg&v=1675186254&fit=crop",
        ],
        [
            "id" => 20,
            "name" => "Bacon king fries con cheddar sauce e bacon bits",
            "price" => "4.40",
            "available" => 1,
            "ingredients" => "patatine fritte con coriandoli di bacon e salsa cheddar",
            "image" => "https://f.roocdn.com/images/menu_items/182573093/item-image.jpg?width=560&height=315&auto=webp&format=jpg&v=1675186254&fit=crop",
        ],
        [
            "id" => 21,
            "name" => "El Pulled Burrito",
            "price" => "13.50",
            "available" => 1,
            "ingredients" => "Riso basmati, pulled pork, fagioli rossi, pico de gallo, panna acida e guacamole",
            "image" => "https://rs-menus-api.roocdn.com/images/88b43cfe-184d-4316-a972-7c2353dddb20/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "id" => 22,
            "name" => "Taco de Chili",
            "price" => "12.00",
            "available" => 1,
            "ingredients" => "Base di lattuga, chili con carne, pico de gallo e guacamole",
            "image" => "https://rs-menus-api.roocdn.com/images/b4b78fa1-8c5e-48b7-b277-13ff33082e52/image.jpeg?width=543&height=305&auto=webp&format=jpg&fit=crop",
        ],
        [
            "id" => 23,
            "name" => "Nachos",
            "price" => "7.00",
            "available" => 1,
            "ingredients" => "Tortillas di mais",
            "image" => "https://rs-menus-api.roocdn.com/images/a68d3915-2e11-4e0a-bdd9-210ec9afd991/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "id" => 24,
            "name" => "Manzo con cinque aromi in salsa piccante",
            "price" => "11.00",
            "available" => 1,
            "ingredients" => "Manzo",
            "image" => "https://rs-menus-api.roocdn.com/images/a68d3915-2e11-4e0a-bdd9-210ec9afd991/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "id" => 25,
            "name" => "Ravioli",
            "price" => "6.00",
            "available" => 1,
            "ingredients" => "Ravioli di maiale",
            "image" => "https://barcalcagno.it/sushi/wp-content/uploads/2019/07/RAVIOLI-R1-R2-.jpg",
        ],
        [
            "id" => 26,
            "name" => "Gamberi",
            "price" => "9.50",
            "available" => 1,
            "ingredients" => "sale e pepe",
            "image" => "https://www.sushiroyal.it/utenti/sushiroyal/uploads/img_6656.jpg",
        ],
        [
            "id" => 27,
            "name" => "Falafel con salsa allo yogurt",
            "price" => "8.50",
            "available" => 1,
            "ingredients" => "Falafel tradizionali con salsa allo yogurt",
            "image" => "https://rs-menus-api.roocdn.com/images/4ec0a438-09c0-4b2d-aff6-7e55e0921f0b/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "id" => 28,
            "name" => "Pita Gyros Falafel",
            "price" => "13.50",
            "available" => 1,
            "ingredients" => "Pita con falafel, hummus, pico de gallo, lattuga e salsa",
            "image" => "https://rs-menus-api.roocdn.com/images/28401375-7661-4cdd-a7e5-dc3f2c3d586c/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
        [
            "id" => 29,
            "name" => "Sprite Vetro",
            "price" => "5.00",
            "available" => 1,
            "ingredients" => "Bibita Sprite",
            "image" => "https://rs-menus-api.roocdn.com/images/eed0caee-9113-4b7c-82ca-dca20d4ceec6/image.jpeg?width=560&height=315&auto=webp&format=jpg&fit=crop",
        ],
    ],
    // "menus" => [
    //     [
    //         "id" => 0,
    //         "name" => "",
    //         "price" => "",
    //         "available" => "",
    //         "ingredients" => "",
    //         "image" => "",
    //     ],
    //     [
    //         "id" => 1,
    //         "name" => "",
    //         "price" => "",
    //         "available" => "",
    //         "ingredients" => "",
    //         "image" => "",
    //     ],
    //     [
    //         "id" => 2,
    //         "name" => "",
    //         "price" => "",
    //         "available" => "",
    //         "ingredients" => "",
    //         "image" => "",
    //     ],
    // ],
];
?>